name: CI workflow

on: pull_request

jobs:
  ci-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Tests e2e
        run: npm run test:e2e:ci
